// Maintains the local mirror of Photos/faces.json — the people/faces database
// generated by the external face-recognition tool. The app never creates
// entries; it only re-keys, renames and removes existing ones when it edits,
// moves or deletes photos, then uploads the updated file back so the external
// tool doesn't lose track of (or re-detect) files the app touched.
//
// Sync policy: the external tool is the source of truth for detections. On
// startup the remote file's pCloud hash is compared with the hash recorded at
// the last sync — if it changed, the remote copy is adopted wholesale. For the
// same reason an upload is aborted (and the remote adopted) when the remote
// changed under us since the last sync.
import { statByPath, downloadJsonFile, uploadJsonToFolder, getFileStat } from './pcloud.js';
import { bulkPutFaces, clearFaces, getFacesEntry, putFacesEntry, deleteFacesEntry, countFaces, getAllFaces } from './db.js';
import { scheduleUpload } from './syncmanager.js';
import { normPcloudHash } from './hashutil.js';
import { log } from './log.js';

const REMOTE_PATH     = '/Photos/faces.json';
const FILENAME        = 'faces.json';
const FILEID_KEY      = 'mappho_faces_fileid';
const META_KEY        = 'mappho_faces_meta';       // { version, generated_at, people }
const REMOTE_HASH_KEY = 'mappho_faces_remotehash'; // pCloud hash of the last synced remote copy
const DIRTY_KEY       = 'mappho_faces_dirty';      // survives restarts so pending edits still upload

let _loaded  = false;
let _loading = null;
let _stats   = null; // cached getPeopleStats() result; null after any mutation

function readMeta() {
  try { return JSON.parse(localStorage.getItem(META_KEY)); } catch { return null; }
}

async function replaceFromRemote(stat) {
  const data = await downloadJsonFile(stat.fileid);
  if (!Array.isArray(data?.entries)) throw new Error('malformed faces.json');
  await clearFaces();
  await bulkPutFaces(data.entries.filter(e => e.hash != null).map(e => ({ ...e, hash: normPcloudHash(e.hash) })));
  // Keep every top-level field except entries (version, generated_at, people,
  // skipped_no_dimensions, …) so write-backs don't drop tool metadata.
  const { entries: _entries, ...meta } = data;
  localStorage.setItem(META_KEY, JSON.stringify(meta));
  localStorage.setItem(FILEID_KEY, String(stat.fileid));
  localStorage.setItem(REMOTE_HASH_KEY, String(stat.hash ?? ''));
  localStorage.removeItem(DIRTY_KEY);
  _stats = null;
  log('Faces', `loaded ${data.entries.length} entries, ${Object.keys(data.people ?? {}).length} people`);
}

// Lazy gate for the maintenance APIs — IDB first, one download attempt if
// empty. Failure leaves the mirror empty (every lookup no-ops) until the next
// app start retries via refreshFaces().
function load() {
  if (_loaded) return Promise.resolve();
  if (!_loading) {
    _loading = (async () => {
      try {
        const local = await countFaces();
        if (local > 0 && readMeta()) {
          log('Faces', `using local mirror — ${local} entries`);
          return;
        }
        log('Faces', 'local mirror empty — downloading from pCloud');
        const stat = await statByPath(REMOTE_PATH);
        await replaceFromRemote(stat);
      } catch (e) {
        log('Faces', `not available: ${e.message}`);
      } finally {
        _loaded = true;
        _loading = null;
      }
    })();
  }
  return _loading;
}

// Startup sync: downloads faces.json when missing locally or regenerated
// remotely by the external tool, and resumes an upload interrupted by an
// app restart. Shares the _loading gate with load() so a lazy load triggered
// by an early edit can't download concurrently with the refresh.
export async function refreshFaces() {
  if (_loading) await _loading;
  _loading = (async () => {
    let stat = null;
    try { stat = await statByPath(REMOTE_PATH); } catch { log('Faces', 'no faces.json on pCloud'); return; }
    try {
      const known = localStorage.getItem(REMOTE_HASH_KEY);
      const local = await countFaces();
      const empty = local === 0 || !readMeta();
      if (empty || String(stat.hash ?? '') !== known) {
        log('Faces', empty ? 'local mirror empty — downloading' : 'remote faces.json changed — re-downloading');
        await replaceFromRemote(stat);
      } else {
        log('Faces', `mirror up to date — ${local} entries`);
        localStorage.setItem(FILEID_KEY, String(stat.fileid)); // track fileid drift
        if (localStorage.getItem(DIRTY_KEY)) { log('Faces', 'pending edits found — resuming upload'); flushFaces(); }
      }
    } catch (e) {
      log('Faces', `refresh failed: ${e.message}`);
    }
  })();
  try { await _loading; } finally { _loaded = true; _loading = null; }
}

function markDirty() {
  localStorage.setItem(DIRTY_KEY, '1');
  _stats = null;
  flushFaces();
}

// Schedules a pCloud upload of the maintained mirror; batched by syncmanager.
export function flushFaces() {
  if (!localStorage.getItem(DIRTY_KEY)) return;
  scheduleUpload('faces', uploadFaces);
}

async function uploadFaces() {
  let stat = null;
  try { stat = await statByPath(REMOTE_PATH); } catch {}
  const known = localStorage.getItem(REMOTE_HASH_KEY);
  if (stat && known && String(stat.hash ?? '') !== known) {
    log('Faces', 'remote regenerated since last sync — adopting it instead of uploading');
    await replaceFromRemote(stat);
    return;
  }
  const entries = await getAllFaces();
  if (!entries.length) { localStorage.removeItem(DIRTY_KEY); return; }
  const meta = readMeta() ?? { version: 2, generated_at: null, people: {} };
  // All tool metadata is passed through; modified_at records the app-side
  // maintenance edits layered on top of the tool's generated_at.
  const json = JSON.stringify({
    ...meta,
    modified_at: new Date().toISOString(),
    entries,
  });
  const folderId = stat?.parentfolderid ?? (await statByPath('/Photos')).folderid;
  const prevFileid = stat?.fileid ?? (Number(localStorage.getItem(FILEID_KEY)) || null);
  const newFileid = await uploadJsonToFolder(folderId, FILENAME, json, prevFileid);
  if (newFileid) {
    localStorage.setItem(FILEID_KEY, String(newFileid));
    const { hash } = await getFileStat(newFileid).catch(() => ({}));
    localStorage.setItem(REMOTE_HASH_KEY, String(hash ?? ''));
  }
  localStorage.removeItem(DIRTY_KEY);
  log('Faces', `uploaded ${entries.length} entries`);
}

// Re-keys/renames a faces entry after an edit changed a file's content hash
// and/or its canonical name. When only `name` is given the folder part of the
// stored path is kept; `path` overrides it entirely (folder moves). No-op for
// files without a faces entry (videos, HEICs, photos with no recognised faces).
export async function renameFacesEntry(oldHash, { newHash = null, name = null, path = null } = {}) {
  await load();
  const key = normPcloudHash(oldHash);
  if (!key) return;
  const entry = await getFacesEntry(key);
  if (!entry) { log('Faces', `no entry for hash ${key} — nothing to update`); return; }
  const newKey  = normPcloudHash(newHash) ?? key;
  const newName = name ?? entry.name;
  const folderPart = entry.path?.includes('/') ? entry.path.slice(0, entry.path.lastIndexOf('/') + 1) : '';
  const newPath = path ?? (name ? folderPart + newName : entry.path);
  if (newKey === key && newName === entry.name && newPath === entry.path) return;
  if (newKey !== key) await deleteFacesEntry(key);
  await putFacesEntry({ ...entry, hash: newKey, name: newName, path: newPath });
  markDirty();
  log('Faces', `${entry.name} → ${newName}${newKey !== key ? ' (re-keyed)' : ''}`);
}

// Removes the faces entry for a photo deleted through the app.
export async function removeFacesEntry(hash) {
  await load();
  const key = normPcloudHash(hash);
  if (!key) return;
  const entry = await getFacesEntry(key);
  if (!entry) { log('Faces', `no entry for hash ${key} — nothing to remove`); return; }
  await deleteFacesEntry(key);
  markDirty();
  log('Faces', `removed entry for deleted ${entry.name}`);
}

// Normalises an entry's face regions to { person, cx, cy, w, h } with all
// coordinates in [0,1] and cx/cy at the region CENTRE (MWG stArea semantics).
// Supports the MWG v2 schema (regions[].area, normalized, centre-based) and
// the legacy v1 schema (faces[] in pixels, top-left, with entry width/height)
// so mirrors that haven't refreshed yet keep working.
export function getFaceRegions(entry) {
  if (!entry) return [];
  if (Array.isArray(entry.regions)) {
    return entry.regions
      .filter(r => r?.area)
      .map(r => ({ person: r.person, cx: r.area.x, cy: r.area.y, w: r.area.w, h: r.area.h }));
  }
  if (Array.isArray(entry.faces) && entry.width && entry.height) {
    return entry.faces.map(f => ({
      person: f.person,
      cx: (f.x + f.w / 2) / entry.width,
      cy: (f.y + f.h / 2) / entry.height,
      w: f.w / entry.width,
      h: f.h / entry.height,
    }));
  }
  return [];
}

// Person ids present in an entry, regardless of whether region coordinates
// are available. getFaceRegions() only returns area-bearing regions (it's
// built for drawing boxes on a single image) — video entries store presence
// only (regions: [{person}], no area, since there's no single frame to place
// a box on), so anything that only cares about "who's in this photo/video",
// not where, should use this instead.
export function getPeoplePresent(entry) {
  if (!entry) return [];
  if (Array.isArray(entry.regions)) {
    return [...new Set(entry.regions.map(r => String(r.person)))];
  }
  if (Array.isArray(entry.faces)) {
    return [...new Set(entry.faces.map(f => String(f.person)))];
  }
  return [];
}

// Lookup APIs for future UI (person filter, name captions, face overlays).
export async function getFacesForHash(hash) {
  await load();
  const key = normPcloudHash(hash);
  const entry = key ? ((await getFacesEntry(key)) ?? null) : null;
  log('Faces', entry
    ? `lookup ${key}: ${entry.name} — ${getFaceRegions(entry).length} face(s)`
    : `lookup ${key ?? '(no hash)'}: no entry`);
  return entry;
}

export function getFacesPeople() {
  return readMeta()?.people ?? {};
}

// Returns the faces entries of every photo/video where ALL given people
// appear together (AND across ids) — a single id is the plain "this
// person's photos/videos" case.
export async function getEntriesForPeople(personIds) {
  await load();
  const ids = personIds.map(String);
  if (!ids.length) return [];
  const all = await getAllFaces();
  const matched = all.filter(e => {
    const present = new Set(getPeoplePresent(e));
    return ids.every(id => present.has(id));
  });
  log('Faces', `people [${ids.join(',')}]: ${matched.length} entries in mirror (AND)`);
  return matched;
}

// Aggregates recognised people with their photo/video counts (a person
// appearing several times in one entry counts once). Sorted by count, then
// name. Cached until a mutation or remote refresh invalidates it.
export async function getPeopleStats() {
  await load();
  if (_stats) { log('Faces', `stats from cache — ${_stats.peopleCount} people`); return _stats; }
  const t0 = Date.now();
  const entries = await getAllFaces();
  const counts = new Map(); // person id (string) → entry count
  for (const e of entries) {
    for (const pid of getPeoplePresent(e)) {
      counts.set(pid, (counts.get(pid) ?? 0) + 1);
    }
  }
  const people = getFacesPeople();
  const list = [...counts.entries()]
    .map(([id, count]) => ({ id, name: people[id] ?? `#${id}`, count }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
  _stats = { peopleCount: list.length, list };
  log('Faces', `stats computed in ${Date.now() - t0}ms — ${list.length} people across ${entries.length} entries`);
  return _stats;
}
