// Maintains the local mirror of Photos/faces.json — the people/faces database
// generated by the external face-recognition tool. The app never creates
// entries; it only re-keys, renames and removes existing ones when it edits,
// moves or deletes photos, then uploads the updated file back so the external
// tool doesn't lose track of (or re-detect) files the app touched.
//
// Sync policy: the external tool is the source of truth for detections. On
// startup the remote file's pCloud hash is compared with the hash recorded at
// the last sync — if it changed, the remote copy is adopted wholesale. For the
// same reason an upload is aborted (and the remote adopted) when the remote
// changed under us since the last sync.
import { statByPath, downloadJsonFile, uploadJsonToFolder, getFileStat } from './pcloud.js';
import { bulkPutFaces, clearFaces, getFacesEntry, putFacesEntry, deleteFacesEntry, countFaces, getAllFaces } from './db.js';
import { scheduleUpload } from './syncmanager.js';
import { log } from './log.js';

const REMOTE_PATH     = '/Photos/faces.json';
const FILENAME        = 'faces.json';
const FILEID_KEY      = 'mappho_faces_fileid';
const META_KEY        = 'mappho_faces_meta';       // { version, generated_at, people }
const REMOTE_HASH_KEY = 'mappho_faces_remotehash'; // pCloud hash of the last synced remote copy
const DIRTY_KEY       = 'mappho_faces_dirty';      // survives restarts so pending edits still upload

let _loaded  = false;
let _loading = null;

// pCloud hashes are uint64, but the app receives them from JSON as JS numbers,
// which round above 2^53. Normalising through Number() puts externally written
// exact values into the same rounded space as the hashes the app stores on its
// own records, so joins always line up.
function normFacesHash(h) {
  if (h == null) return null;
  const n = Number(h);
  return Number.isFinite(n) ? String(n) : String(h);
}

function readMeta() {
  try { return JSON.parse(localStorage.getItem(META_KEY)); } catch { return null; }
}

async function replaceFromRemote(stat) {
  const data = await downloadJsonFile(stat.fileid);
  if (!Array.isArray(data?.entries)) throw new Error('malformed faces.json');
  await clearFaces();
  await bulkPutFaces(data.entries.filter(e => e.hash != null).map(e => ({ ...e, hash: normFacesHash(e.hash) })));
  localStorage.setItem(META_KEY, JSON.stringify({ version: data.version ?? 1, generated_at: data.generated_at ?? null, people: data.people ?? {} }));
  localStorage.setItem(FILEID_KEY, String(stat.fileid));
  localStorage.setItem(REMOTE_HASH_KEY, String(stat.hash ?? ''));
  localStorage.removeItem(DIRTY_KEY);
  log('Faces', `loaded ${data.entries.length} entries, ${Object.keys(data.people ?? {}).length} people`);
}

// Lazy gate for the maintenance APIs — IDB first, one download attempt if
// empty. Failure leaves the mirror empty (every lookup no-ops) until the next
// app start retries via refreshFaces().
function load() {
  if (_loaded) return Promise.resolve();
  if (!_loading) {
    _loading = (async () => {
      try {
        if ((await countFaces()) > 0 && readMeta()) return;
        const stat = await statByPath(REMOTE_PATH);
        await replaceFromRemote(stat);
      } catch (e) {
        log('Faces', `not available: ${e.message}`);
      } finally {
        _loaded = true;
        _loading = null;
      }
    })();
  }
  return _loading;
}

// Startup sync: downloads faces.json when missing locally or regenerated
// remotely by the external tool, and resumes an upload interrupted by an
// app restart. Shares the _loading gate with load() so a lazy load triggered
// by an early edit can't download concurrently with the refresh.
export async function refreshFaces() {
  if (_loading) await _loading;
  _loading = (async () => {
    let stat = null;
    try { stat = await statByPath(REMOTE_PATH); } catch { return; }
    try {
      const known = localStorage.getItem(REMOTE_HASH_KEY);
      const empty = (await countFaces()) === 0 || !readMeta();
      if (empty || String(stat.hash ?? '') !== known) {
        await replaceFromRemote(stat);
      } else {
        localStorage.setItem(FILEID_KEY, String(stat.fileid)); // track fileid drift
        if (localStorage.getItem(DIRTY_KEY)) flushFaces();
      }
    } catch (e) {
      log('Faces', `refresh failed: ${e.message}`);
    }
  })();
  try { await _loading; } finally { _loaded = true; _loading = null; }
}

function markDirty() {
  localStorage.setItem(DIRTY_KEY, '1');
  flushFaces();
}

// Schedules a pCloud upload of the maintained mirror; batched by syncmanager.
export function flushFaces() {
  if (!localStorage.getItem(DIRTY_KEY)) return;
  scheduleUpload('faces', uploadFaces);
}

async function uploadFaces() {
  let stat = null;
  try { stat = await statByPath(REMOTE_PATH); } catch {}
  const known = localStorage.getItem(REMOTE_HASH_KEY);
  if (stat && known && String(stat.hash ?? '') !== known) {
    log('Faces', 'remote regenerated since last sync — adopting it instead of uploading');
    await replaceFromRemote(stat);
    return;
  }
  const entries = await getAllFaces();
  if (!entries.length) { localStorage.removeItem(DIRTY_KEY); return; }
  const meta = readMeta() ?? { version: 1, generated_at: null, people: {} };
  // generated_at stays the external tool's timestamp; modified_at records the
  // app-side maintenance edits layered on top of that generation.
  const json = JSON.stringify({
    version: meta.version,
    generated_at: meta.generated_at,
    modified_at: new Date().toISOString(),
    people: meta.people,
    entries,
  });
  const folderId = stat?.parentfolderid ?? (await statByPath('/Photos')).folderid;
  const prevFileid = stat?.fileid ?? (Number(localStorage.getItem(FILEID_KEY)) || null);
  const newFileid = await uploadJsonToFolder(folderId, FILENAME, json, prevFileid);
  if (newFileid) {
    localStorage.setItem(FILEID_KEY, String(newFileid));
    const { hash } = await getFileStat(newFileid).catch(() => ({}));
    localStorage.setItem(REMOTE_HASH_KEY, String(hash ?? ''));
  }
  localStorage.removeItem(DIRTY_KEY);
  log('Faces', `uploaded ${entries.length} entries`);
}

// Re-keys/renames a faces entry after an edit changed a file's content hash
// and/or its canonical name. When only `name` is given the folder part of the
// stored path is kept; `path` overrides it entirely (folder moves). No-op for
// files without a faces entry (videos, HEICs, photos with no recognised faces).
export async function renameFacesEntry(oldHash, { newHash = null, name = null, path = null } = {}) {
  await load();
  const key = normFacesHash(oldHash);
  if (!key) return;
  const entry = await getFacesEntry(key);
  if (!entry) return;
  const newKey  = normFacesHash(newHash) ?? key;
  const newName = name ?? entry.name;
  const folderPart = entry.path?.includes('/') ? entry.path.slice(0, entry.path.lastIndexOf('/') + 1) : '';
  const newPath = path ?? (name ? folderPart + newName : entry.path);
  if (newKey === key && newName === entry.name && newPath === entry.path) return;
  if (newKey !== key) await deleteFacesEntry(key);
  await putFacesEntry({ ...entry, hash: newKey, name: newName, path: newPath });
  markDirty();
  log('Faces', `${entry.name} → ${newName}${newKey !== key ? ' (re-keyed)' : ''}`);
}

// Removes the faces entry for a photo deleted through the app.
export async function removeFacesEntry(hash) {
  await load();
  const key = normFacesHash(hash);
  if (!key) return;
  const entry = await getFacesEntry(key);
  if (!entry) return;
  await deleteFacesEntry(key);
  markDirty();
  log('Faces', `removed entry for deleted ${entry.name}`);
}

// Lookup APIs for future UI (person filter, name captions, face overlays).
export async function getFacesForHash(hash) {
  await load();
  const key = normFacesHash(hash);
  return key ? ((await getFacesEntry(key)) ?? null) : null;
}

export function getFacesPeople() {
  return readMeta()?.people ?? {};
}
