// Maintains the local mirror of Photos/locations.json — scene/place
// classifications (e.g. "mountains", "beach", "street") generated by an
// external tool. Same identity model and sync policy as faces.js: the app
// never creates entries, only re-keys/renames/removes existing ones when it
// edits, moves or deletes photos, and the external tool remains the source
// of truth for classifications (remote changes are adopted wholesale rather
// than merged).
import { statByPath, downloadJsonFile, uploadJsonToFolder, getFileStat } from './pcloud.js';
import { bulkPutLocations, clearLocations, getLocationsEntry, putLocationsEntry, deleteLocationsEntry, countLocations, getAllLocations } from './db.js';
import { scheduleUpload } from './syncmanager.js';
import { normPcloudHash } from './hashutil.js';
import { log } from './log.js';

const REMOTE_PATH     = '/Photos/locations.json';
const FILENAME        = 'locations.json';
const FILEID_KEY      = 'mappho_locations_fileid';
const META_KEY        = 'mappho_locations_meta';       // { version, generated_at, categories }
const REMOTE_HASH_KEY = 'mappho_locations_remotehash'; // pCloud hash of the last synced remote copy
const DIRTY_KEY       = 'mappho_locations_dirty';      // survives restarts so pending edits still upload

let _loaded  = false;
let _loading = null;
let _stats   = null; // cached getLocationStats() result; null after any mutation

function readMeta() {
  try { return JSON.parse(localStorage.getItem(META_KEY)); } catch { return null; }
}

async function replaceFromRemote(stat) {
  const data = await downloadJsonFile(stat.fileid);
  if (!Array.isArray(data?.entries)) throw new Error('malformed locations.json');
  await clearLocations();
  await bulkPutLocations(data.entries.filter(e => e.hash != null).map(e => ({ ...e, hash: normPcloudHash(e.hash) })));
  // Keep every top-level field except entries (version, generated_at,
  // categories, …) so write-backs don't drop tool metadata.
  const { entries: _entries, ...meta } = data;
  localStorage.setItem(META_KEY, JSON.stringify(meta));
  localStorage.setItem(FILEID_KEY, String(stat.fileid));
  localStorage.setItem(REMOTE_HASH_KEY, String(stat.hash ?? ''));
  localStorage.removeItem(DIRTY_KEY);
  _stats = null;
  log('Locations', `loaded ${data.entries.length} entries, ${data.categories?.length ?? 0} categories`);
}

// Lazy gate for the maintenance APIs — IDB first, one download attempt if
// empty. Failure leaves the mirror empty (every lookup no-ops) until the next
// app start retries via refreshLocations().
function load() {
  if (_loaded) return Promise.resolve();
  if (!_loading) {
    _loading = (async () => {
      try {
        const local = await countLocations();
        if (local > 0 && readMeta()) {
          log('Locations', `using local mirror — ${local} entries`);
          return;
        }
        log('Locations', 'local mirror empty — downloading from pCloud');
        const stat = await statByPath(REMOTE_PATH);
        await replaceFromRemote(stat);
      } catch (e) {
        log('Locations', `not available: ${e.message}`);
      } finally {
        _loaded = true;
        _loading = null;
      }
    })();
  }
  return _loading;
}

// Startup sync: downloads locations.json when missing locally or regenerated
// remotely by the external tool, and resumes an upload interrupted by an app
// restart. Shares the _loading gate with load() so a lazy load triggered by
// an early edit can't download concurrently with the refresh.
export async function refreshLocations() {
  if (_loading) await _loading;
  _loading = (async () => {
    let stat = null;
    try { stat = await statByPath(REMOTE_PATH); } catch { log('Locations', 'no locations.json on pCloud'); return; }
    try {
      const known = localStorage.getItem(REMOTE_HASH_KEY);
      const local = await countLocations();
      const empty = local === 0 || !readMeta();
      if (empty || String(stat.hash ?? '') !== known) {
        log('Locations', empty ? 'local mirror empty — downloading' : 'remote locations.json changed — re-downloading');
        await replaceFromRemote(stat);
      } else {
        log('Locations', `mirror up to date — ${local} entries`);
        localStorage.setItem(FILEID_KEY, String(stat.fileid)); // track fileid drift
        if (localStorage.getItem(DIRTY_KEY)) { log('Locations', 'pending edits found — resuming upload'); flushLocations(); }
      }
    } catch (e) {
      log('Locations', `refresh failed: ${e.message}`);
    }
  })();
  try { await _loading; } finally { _loaded = true; _loading = null; }
}

function markDirty() {
  localStorage.setItem(DIRTY_KEY, '1');
  _stats = null;
  flushLocations();
}

// Schedules a pCloud upload of the maintained mirror; batched by syncmanager.
export function flushLocations() {
  if (!localStorage.getItem(DIRTY_KEY)) return;
  scheduleUpload('locations', uploadLocations);
}

async function uploadLocations() {
  let stat = null;
  try { stat = await statByPath(REMOTE_PATH); } catch {}
  const known = localStorage.getItem(REMOTE_HASH_KEY);
  if (stat && known && String(stat.hash ?? '') !== known) {
    log('Locations', 'remote regenerated since last sync — adopting it instead of uploading');
    await replaceFromRemote(stat);
    return;
  }
  const entries = await getAllLocations();
  if (!entries.length) { localStorage.removeItem(DIRTY_KEY); return; }
  const meta = readMeta() ?? { version: 1, generated_at: null, categories: [] };
  // All tool metadata is passed through; modified_at records the app-side
  // maintenance edits layered on top of the tool's generated_at.
  const json = JSON.stringify({
    ...meta,
    modified_at: new Date().toISOString(),
    entries,
  });
  const folderId = stat?.parentfolderid ?? (await statByPath('/Photos')).folderid;
  const prevFileid = stat?.fileid ?? (Number(localStorage.getItem(FILEID_KEY)) || null);
  const newFileid = await uploadJsonToFolder(folderId, FILENAME, json, prevFileid);
  if (newFileid) {
    localStorage.setItem(FILEID_KEY, String(newFileid));
    const { hash } = await getFileStat(newFileid).catch(() => ({}));
    localStorage.setItem(REMOTE_HASH_KEY, String(hash ?? ''));
  }
  localStorage.removeItem(DIRTY_KEY);
  log('Locations', `uploaded ${entries.length} entries`);
}

// Re-keys/renames a locations entry after an edit changed a file's content
// hash and/or its canonical name. When only `name` is given the folder part
// of the stored path is kept; `path` overrides it entirely (folder moves).
// No-op for files without a locations entry (videos, photos with no scene
// classification).
export async function renameLocationsEntry(oldHash, { newHash = null, name = null, path = null } = {}) {
  await load();
  const key = normPcloudHash(oldHash);
  if (!key) return;
  const entry = await getLocationsEntry(key);
  if (!entry) { log('Locations', `no entry for hash ${key} — nothing to update`); return; }
  const newKey  = normPcloudHash(newHash) ?? key;
  const newName = name ?? entry.name;
  const folderPart = entry.path?.includes('/') ? entry.path.slice(0, entry.path.lastIndexOf('/') + 1) : '';
  const newPath = path ?? (name ? folderPart + newName : entry.path);
  if (newKey === key && newName === entry.name && newPath === entry.path) return;
  if (newKey !== key) await deleteLocationsEntry(key);
  await putLocationsEntry({ ...entry, hash: newKey, name: newName, path: newPath });
  markDirty();
  log('Locations', `${entry.name} → ${newName}${newKey !== key ? ' (re-keyed)' : ''}`);
}

// Removes the locations entry for a photo deleted through the app.
export async function removeLocationsEntry(hash) {
  await load();
  const key = normPcloudHash(hash);
  if (!key) return;
  const entry = await getLocationsEntry(key);
  if (!entry) { log('Locations', `no entry for hash ${key} — nothing to remove`); return; }
  await deleteLocationsEntry(key);
  markDirty();
  log('Locations', `removed entry for deleted ${entry.name}`);
}

export async function getLocationsForHash(hash) {
  await load();
  const key = normPcloudHash(hash);
  const entry = key ? ((await getLocationsEntry(key)) ?? null) : null;
  log('Locations', entry
    ? `lookup ${key}: ${entry.name} — ${(entry.tags ?? []).map(t => t.category).join(', ')}`
    : `lookup ${key ?? '(no hash)'}: no entry`);
  return entry;
}

// Returns the locations entries of every photo tagged with ALL given
// categories (AND across categories) — a single category is the plain
// "photos tagged with this place" case.
export async function getEntriesForLocations(categories) {
  await load();
  const cats = categories.map(String);
  if (!cats.length) return [];
  const all = await getAllLocations();
  const matched = all.filter(e => {
    const present = new Set((e.tags ?? []).map(t => String(t.category)));
    return cats.every(c => present.has(c));
  });
  log('Locations', `categories [${cats.join(',')}]: ${matched.length} photos in mirror (AND)`);
  return matched;
}

// Aggregates classified categories with their photo counts. Sorted by count,
// then name. Cached until a mutation or remote refresh invalidates it.
export async function getLocationStats() {
  await load();
  if (_stats) { log('Locations', `stats from cache — ${_stats.categoryCount} categories`); return _stats; }
  const t0 = Date.now();
  const entries = await getAllLocations();
  const counts = new Map(); // category → photo count
  for (const e of entries) {
    for (const t of e.tags ?? []) {
      const cat = String(t.category);
      counts.set(cat, (counts.get(cat) ?? 0) + 1);
    }
  }
  const list = [...counts.entries()]
    .map(([id, count]) => ({ id, name: id, count }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
  _stats = { categoryCount: list.length, list };
  log('Locations', `stats computed in ${Date.now() - t0}ms — ${list.length} categories across ${entries.length} photos`);
  return _stats;
}
